//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCase.Controller.Commands {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommandDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandDescription() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XCase.Controller.Commands.CommandDescription", typeof(CommandDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new association class to model and diagram.
        /// </summary>
        public static string ADD_ASSOCIATION_CLASS_MACRO {
            get {
                return ResourceManager.GetString("ADD_ASSOCIATION_CLASS_MACRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another association end..
        /// </summary>
        public static string ADD_ASSOCIATION_END {
            get {
                return ResourceManager.GetString("ADD_ASSOCIATION_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new association to model and diagram.
        /// </summary>
        public static string ADD_ASSOCIATION_MACRO {
            get {
                return ResourceManager.GetString("ADD_ASSOCIATION_MACRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add class&apos; attribute.
        /// </summary>
        public static string ADD_ATTRIBUTE {
            get {
                return ResourceManager.GetString("ADD_ATTRIBUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new class to model and diagram.
        /// </summary>
        public static string ADD_CLASS_MACRO {
            get {
                return ResourceManager.GetString("ADD_CLASS_MACRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new comment to model and diagram.
        /// </summary>
        public static string ADD_COMMENT_MACRO {
            get {
                return ResourceManager.GetString("ADD_COMMENT_MACRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds an alement to a diagram.
        /// </summary>
        public static string ADD_ELEMENT_TO_DIAGRAM {
            get {
                return ResourceManager.GetString("ADD_ELEMENT_TO_DIAGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new generalization to model and diagram.
        /// </summary>
        public static string ADD_GENERALIZATION_MACRO {
            get {
                return ResourceManager.GetString("ADD_GENERALIZATION_MACRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add model association.
        /// </summary>
        public static string ADD_MODEL_ASSOCIATION {
            get {
                return ResourceManager.GetString("ADD_MODEL_ASSOCIATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add model association class.
        /// </summary>
        public static string ADD_MODEL_ASSOCIATION_CLASS {
            get {
                return ResourceManager.GetString("ADD_MODEL_ASSOCIATION_CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add model class.
        /// </summary>
        public static string ADD_MODEL_CLASS {
            get {
                return ResourceManager.GetString("ADD_MODEL_CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add model comment.
        /// </summary>
        public static string ADD_MODEL_COMMENT {
            get {
                return ResourceManager.GetString("ADD_MODEL_COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add model generalization.
        /// </summary>
        public static string ADD_MODEL_GENERALIZATION {
            get {
                return ResourceManager.GetString("ADD_MODEL_GENERALIZATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a new Stereotype.
        /// </summary>
        public static string ADD_MODEL_STEREOTYPE {
            get {
                return ResourceManager.GetString("ADD_MODEL_STEREOTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a nesting join to a PSM Association.
        /// </summary>
        public static string ADD_NESTING_JOIN {
            get {
                return ResourceManager.GetString("ADD_NESTING_JOIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add class&apos; operation.
        /// </summary>
        public static string ADD_OPERATION {
            get {
                return ResourceManager.GetString("ADD_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new package.
        /// </summary>
        public static string ADD_PACKAGE {
            get {
                return ResourceManager.GetString("ADD_PACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an PIM diagram.
        /// </summary>
        public static string ADD_PIM_DIAGRAM {
            get {
                return ResourceManager.GetString("ADD_PIM_DIAGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a PSM Association.
        /// </summary>
        public static string ADD_PSM_ASSOCIATION {
            get {
                return ResourceManager.GetString("ADD_PSM_ASSOCIATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a PSM Attribute.
        /// </summary>
        public static string ADD_PSM_ATTRIBUTE {
            get {
                return ResourceManager.GetString("ADD_PSM_ATTRIBUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a PSM Attribute Container.
        /// </summary>
        public static string ADD_PSM_ATTRIBUTE_CONTAINER {
            get {
                return ResourceManager.GetString("ADD_PSM_ATTRIBUTE_CONTAINER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add PSM Class children.
        /// </summary>
        public static string ADD_PSM_CHILDREN_MACRO {
            get {
                return ResourceManager.GetString("ADD_PSM_CHILDREN_MACRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derive a new PSM Class.
        /// </summary>
        public static string ADD_PSM_CLASS {
            get {
                return ResourceManager.GetString("ADD_PSM_CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a PSM Content Choice.
        /// </summary>
        public static string ADD_PSM_CONTENT_CHOICE {
            get {
                return ResourceManager.GetString("ADD_PSM_CONTENT_CHOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a PSM Content Container.
        /// </summary>
        public static string ADD_PSM_CONTENT_CONTAINER {
            get {
                return ResourceManager.GetString("ADD_PSM_CONTENT_CONTAINER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an PSM diagram.
        /// </summary>
        public static string ADD_PSM_DIAGRAM {
            get {
                return ResourceManager.GetString("ADD_PSM_DIAGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a root to a PSM Diagram.
        /// </summary>
        public static string ADD_PSM_DIAGRAM_ROOT {
            get {
                return ResourceManager.GetString("ADD_PSM_DIAGRAM_ROOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Element name label.
        /// </summary>
        public static string ALIGN_ELEMENT_NAME {
            get {
                return ResourceManager.GetString("ALIGN_ELEMENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply a Stereotype to a class.
        /// </summary>
        public static string APPLY_MODEL_STEREOTYPE {
            get {
                return ResourceManager.GetString("APPLY_MODEL_STEREOTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply a new Stereotype to a class.
        /// </summary>
        public static string APPLY_NEW_MODEL_STEREOTYPE {
            get {
                return ResourceManager.GetString("APPLY_NEW_MODEL_STEREOTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change association end aggregation.
        /// </summary>
        public static string CHANGE_AGGREGATION {
            get {
                return ResourceManager.GetString("CHANGE_AGGREGATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change  &quot;any attribute&quot; definition.
        /// </summary>
        public static string CHANGE_ANY_ATTRIBUTE {
            get {
                return ResourceManager.GetString("CHANGE_ANY_ATTRIBUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change attribute&apos;s default value.
        /// </summary>
        public static string CHANGE_ATTRIBUTE_DEFAULT {
            get {
                return ResourceManager.GetString("CHANGE_ATTRIBUTE_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change type of an attribute.
        /// </summary>
        public static string CHANGE_ATTRIBUTE_TYPE {
            get {
                return ResourceManager.GetString("CHANGE_ATTRIBUTE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change comment text.
        /// </summary>
        public static string CHANGE_COMMENT {
            get {
                return ResourceManager.GetString("CHANGE_COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change diagram target namespace.
        /// </summary>
        public static string CHANGE_DIAGRAM_TARGET_NAMESPACE {
            get {
                return ResourceManager.GetString("CHANGE_DIAGRAM_TARGET_NAMESPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes PSM class Element Name.
        /// </summary>
        public static string CHANGE_ELEMENT_NAME {
            get {
                return ResourceManager.GetString("CHANGE_ELEMENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change element multiplicity.
        /// </summary>
        public static string CHANGE_MULTIPLICITY {
            get {
                return ResourceManager.GetString("CHANGE_MULTIPLICITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change diagram reference namespace.
        /// </summary>
        public static string CHANGE_REFERENCE_NAMESPACE {
            get {
                return ResourceManager.GetString("CHANGE_REFERENCE_NAMESPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change diagram reference namespace prefix.
        /// </summary>
        public static string CHANGE_REFERENCE_NAMESPACE_PREFIX {
            get {
                return ResourceManager.GetString("CHANGE_REFERENCE_NAMESPACE_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change referenced diagram.
        /// </summary>
        public static string CHANGE_REFERENCED_DIAGRAM {
            get {
                return ResourceManager.GetString("CHANGE_REFERENCED_DIAGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change diagram reference schema location.
        /// </summary>
        public static string CHANGE_SCHEMA_LOCATION {
            get {
                return ResourceManager.GetString("CHANGE_SCHEMA_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete elements from model.
        /// </summary>
        public static string DELETE_FROM_MODEL {
            get {
                return ResourceManager.GetString("DELETE_FROM_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derive a PSM Class to an existing PSM Diagram.
        /// </summary>
        public static string DERIVE_PSM_CLASS_DIAGRAM {
            get {
                return ResourceManager.GetString("DERIVE_PSM_CLASS_DIAGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derive a PSM Class to a new PSM Diagram.
        /// </summary>
        public static string DERIVE_PSM_CLASS_NEW_DIAGRAM {
            get {
                return ResourceManager.GetString("DERIVE_PSM_CLASS_NEW_DIAGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update diagram reference macro command.
        /// </summary>
        public static string DIAGRAM_REFERENCE_MACRO {
            get {
                return ResourceManager.GetString("DIAGRAM_REFERENCE_MACRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate diagram in project..
        /// </summary>
        public static string DUPLICATE_DIAGRAM {
            get {
                return ResourceManager.GetString("DUPLICATE_DIAGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group by.
        /// </summary>
        public static string GROUP_BY {
            get {
                return ResourceManager.GetString("GROUP_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Element Holder type.
        /// </summary>
        public static string HOLDER_CONVERTOR {
            get {
                return ResourceManager.GetString("HOLDER_CONVERTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include elements to a diagram.
        /// </summary>
        public static string INCLUDE_ELEMENTS {
            get {
                return ResourceManager.GetString("INCLUDE_ELEMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalidate command stack.
        /// </summary>
        public static string INVALIDATE_STACK {
            get {
                return ResourceManager.GetString("INVALIDATE_STACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/hide label.
        /// </summary>
        public static string LABEL_SHOWHIDE {
            get {
                return ResourceManager.GetString("LABEL_SHOWHIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move a class to a package.
        /// </summary>
        public static string MOVE_CLASS_TO_PACKAGE {
            get {
                return ResourceManager.GetString("MOVE_CLASS_TO_PACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move element on a diagram.
        /// </summary>
        public static string MOVE_ELEMENT {
            get {
                return ResourceManager.GetString("MOVE_ELEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move some points of junction.
        /// </summary>
        public static string MOVE_JUNCTION_POINTS {
            get {
                return ResourceManager.GetString("MOVE_JUNCTION_POINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move junction segment.
        /// </summary>
        public static string MOVE_JUNCTION_SEGMENT {
            get {
                return ResourceManager.GetString("MOVE_JUNCTION_SEGMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move macro command.
        /// </summary>
        public static string MOVE_MACRO {
            get {
                return ResourceManager.GetString("MOVE_MACRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move a package.
        /// </summary>
        public static string MOVE_PACKAGE {
            get {
                return ResourceManager.GetString("MOVE_PACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} moved points).
        /// </summary>
        public static string MOVED_POINTS {
            get {
                return ResourceManager.GetString("MOVED_POINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new simple type.
        /// </summary>
        public static string NEW_SIMPLE_TYPE {
            get {
                return ResourceManager.GetString("NEW_SIMPLE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propagate PIMLess attribute to PIM.
        /// </summary>
        public static string PROPAGATE_PIMLESS {
            get {
                return ResourceManager.GetString("PROPAGATE_PIMLESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds attribute to a PSM Class.
        /// </summary>
        public static string PSM_ADD_ATTRIBUTE {
            get {
                return ResourceManager.GetString("PSM_ADD_ATTRIBUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference another PSM diagram.
        /// </summary>
        public static string PSM_ADD_DIAGRAM_REFERENCE {
            get {
                return ResourceManager.GetString("PSM_ADD_DIAGRAM_REFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a subclass of a class to the diagram.
        /// </summary>
        public static string PSM_ADD_SPECIFICATIONS {
            get {
                return ResourceManager.GetString("PSM_ADD_SPECIFICATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move attributes to attribute container.
        /// </summary>
        public static string PSM_ATTRIBUTE_CONTAINER {
            get {
                return ResourceManager.GetString("PSM_ATTRIBUTE_CONTAINER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change alias of an atribute on a PSM diagram.
        /// </summary>
        public static string PSM_CHANGE_ATTRIBUTE_ALIAS {
            get {
                return ResourceManager.GetString("PSM_CHANGE_ATTRIBUTE_ALIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update PSMClass&apos; - abstract/not-abstract.
        /// </summary>
        public static string PSM_CLASS_ALTER_ABSTRACT {
            get {
                return ResourceManager.GetString("PSM_CLASS_ALTER_ABSTRACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a PSM Class to a PSM Diagram.
        /// </summary>
        public static string PSM_CLASS_TO_DIAGRAM {
            get {
                return ResourceManager.GetString("PSM_CLASS_TO_DIAGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a PSM Class to a PSM Diagram.
        /// </summary>
        public static string PSM_CLASS_TO_DIAGRAM_MODELCOMMAND {
            get {
                return ResourceManager.GetString("PSM_CLASS_TO_DIAGRAM_MODELCOMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder components.
        /// </summary>
        public static string PSM_COMPONENT_REORDER {
            get {
                return ResourceManager.GetString("PSM_COMPONENT_REORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component(s) moved..
        /// </summary>
        public static string PSM_COMPONENTS_MOVED {
            get {
                return ResourceManager.GetString("PSM_COMPONENTS_MOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut association to root.
        /// </summary>
        public static string PSM_CUT_ASSOCIATION_TO_ROOT {
            get {
                return ResourceManager.GetString("PSM_CUT_ASSOCIATION_TO_ROOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude attributes of a class in from a PSM diagram.
        /// </summary>
        public static string PSM_EXCLUDE_CLASS_ATTRIBUTES {
            get {
                return ResourceManager.GetString("PSM_EXCLUDE_CLASS_ATTRIBUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include/exclude attributes of a class in a PSM diagram.
        /// </summary>
        public static string PSM_INCLUDE_CLASS_ATTRIBUTES {
            get {
                return ResourceManager.GetString("PSM_INCLUDE_CLASS_ATTRIBUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove attribute container from the diagram.
        /// </summary>
        public static string PSM_LEAVE_OUT_ATTRIBUTE_CONTAINER {
            get {
                return ResourceManager.GetString("PSM_LEAVE_OUT_ATTRIBUTE_CONTAINER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove class union from the diagram.
        /// </summary>
        public static string PSM_LEAVE_OUT_CLASS_UNION {
            get {
                return ResourceManager.GetString("PSM_LEAVE_OUT_CLASS_UNION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove structural elements from the diagram.
        /// </summary>
        public static string PSM_LEAVE_OUT_STRUCTURAL_ELEMENTS {
            get {
                return ResourceManager.GetString("PSM_LEAVE_OUT_STRUCTURAL_ELEMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove content choice / conent container from the diagram.
        /// </summary>
        public static string PSM_LEAVE_OUT_SUPERORDINATE_COMPONENT {
            get {
                return ResourceManager.GetString("PSM_LEAVE_OUT_SUPERORDINATE_COMPONENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alter list of class attributes.
        /// </summary>
        public static string PSM_MANAGE_ATTRIBUTES {
            get {
                return ResourceManager.GetString("PSM_MANAGE_ATTRIBUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes added to class union..
        /// </summary>
        public static string PSM_MORE_CLASSES_TO_UNION {
            get {
                return ResourceManager.GetString("PSM_MORE_CLASSES_TO_UNION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move attribues from attribute container back to class.
        /// </summary>
        public static string PSM_MOVE_ATTRIBUTES_BACK_TO_CLASS {
            get {
                return ResourceManager.GetString("PSM_MOVE_ATTRIBUTES_BACK_TO_CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves component from content choice or content container.
        /// </summary>
        public static string PSM_MOVE_CONTENT_FROM_CONTAINER {
            get {
                return ResourceManager.GetString("PSM_MOVE_CONTENT_FROM_CONTAINER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove PSM diagram refernce.
        /// </summary>
        public static string PSM_REMOVE_DIAGRAM_REFERENCE {
            get {
                return ResourceManager.GetString("PSM_REMOVE_DIAGRAM_REFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect all components of the source to the target.
        /// </summary>
        public static string RECONNECT_COMPONENTS {
            get {
                return ResourceManager.GetString("RECONNECT_COMPONENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change diagram reference local/external.
        /// </summary>
        public static string REFERENCE_LOCAL_EXTERNAL {
            get {
                return ResourceManager.GetString("REFERENCE_LOCAL_EXTERNAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes an end fom an association. .
        /// </summary>
        public static string REMOVE_ASSOCIATION_END {
            get {
                return ResourceManager.GetString("REMOVE_ASSOCIATION_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove class&apos; attribute.
        /// </summary>
        public static string REMOVE_ATTRIBUTE {
            get {
                return ResourceManager.GetString("REMOVE_ATTRIBUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a diagram.
        /// </summary>
        public static string REMOVE_DIAGRAM {
            get {
                return ResourceManager.GetString("REMOVE_DIAGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove an element from a diagram.
        /// </summary>
        public static string REMOVE_FROM_DIAGRAM {
            get {
                return ResourceManager.GetString("REMOVE_FROM_DIAGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove element from diagram with dependencies.
        /// </summary>
        public static string REMOVE_FROM_DIAGRAM_MACRO {
            get {
                return ResourceManager.GetString("REMOVE_FROM_DIAGRAM_MACRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove element from model with dependencies.
        /// </summary>
        public static string REMOVE_FROM_MODEL_MACRO {
            get {
                return ResourceManager.GetString("REMOVE_FROM_MODEL_MACRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove class&apos; operation.
        /// </summary>
        public static string REMOVE_OPERATION {
            get {
                return ResourceManager.GetString("REMOVE_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a package.
        /// </summary>
        public static string REMOVE_PACKAGE {
            get {
                return ResourceManager.GetString("REMOVE_PACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a package and its classes and nested packages.
        /// </summary>
        public static string REMOVE_PACKAGE_MACRO {
            get {
                return ResourceManager.GetString("REMOVE_PACKAGE_MACRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a PSM Attribute.
        /// </summary>
        public static string REMOVE_PSM_ATTRIBUTE {
            get {
                return ResourceManager.GetString("REMOVE_PSM_ATTRIBUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a PSM Superordinate component.
        /// </summary>
        public static string REMOVE_PSM_SUPERORDINATE {
            get {
                return ResourceManager.GetString("REMOVE_PSM_SUPERORDINATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove PSM Class from roots.
        /// </summary>
        public static string REMOVE_PSMCLASS_FROM_ROOTS {
            get {
                return ResourceManager.GetString("REMOVE_PSMCLASS_FROM_ROOTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename a diagram.
        /// </summary>
        public static string RENAME_DIAGRAM {
            get {
                return ResourceManager.GetString("RENAME_DIAGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename element.
        /// </summary>
        public static string RENAME_ELEMENT {
            get {
                return ResourceManager.GetString("RENAME_ELEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename project namespace.
        /// </summary>
        public static string RENAME_PROJECT_NAMESPACE {
            get {
                return ResourceManager.GetString("RENAME_PROJECT_NAMESPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize element on a diagram.
        /// </summary>
        public static string RESIZE_ELEMENT {
            get {
                return ResourceManager.GetString("RESIZE_ELEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize element on a diagram.
        /// </summary>
        public static string RESIZE_MACRO {
            get {
                return ResourceManager.GetString("RESIZE_MACRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set represented PSM Class.
        /// </summary>
        public static string SET_REPRESENTED_CLASS {
            get {
                return ResourceManager.GetString("SET_REPRESENTED_CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switches view of an association between view with an association diamond and without it. .
        /// </summary>
        public static string SWITCH_DIAMOND {
            get {
                return ResourceManager.GetString("SWITCH_DIAMOND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update association.
        /// </summary>
        public static string UPDATE_ASSOCIATION_MACRO {
            get {
                return ResourceManager.GetString("UPDATE_ASSOCIATION_MACRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update class.
        /// </summary>
        public static string UPDATE_CLASS_MACRO {
            get {
                return ResourceManager.GetString("UPDATE_CLASS_MACRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update operation .
        /// </summary>
        public static string UPDATE_OPERATION_MACRO {
            get {
                return ResourceManager.GetString("UPDATE_OPERATION_MACRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update package.
        /// </summary>
        public static string UPDATE_PACKAGE_MACRO {
            get {
                return ResourceManager.GetString("UPDATE_PACKAGE_MACRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update property.
        /// </summary>
        public static string UPDATE_PROPERTY_MACRO {
            get {
                return ResourceManager.GetString("UPDATE_PROPERTY_MACRO", resourceCulture);
            }
        }
    }
}
