//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCase.Controller.Commands {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandError {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandError() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XCase.Controller.Commands.CommandError", typeof(CommandError).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed end does not belong to the association. .
        /// </summary>
        internal static string BAD_REMOVED_ASSOCIATION_END {
            get {
                return ResourceManager.GetString("BAD_REMOVED_ASSOCIATION_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This association has only two ends. No ends can be removed. .
        /// </summary>
        internal static string CANNOT_REMOVE_END_FROM_BINARY_ASSOCIATION {
            get {
                return ResourceManager.GetString("CANNOT_REMOVE_END_FROM_BINARY_ASSOCIATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add point with index 0 which is reserved for start point, only inner points can be added..
        /// </summary>
        internal static string CMDERR_ADD_BEFORE_STARTPOINT {
            get {
                return ResourceManager.GetString("CMDERR_ADD_BEFORE_STARTPOINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add points behind end point, only inner points can be added..
        /// </summary>
        internal static string CMDERR_ADD_BEHIND_ENDPOINT {
            get {
                return ResourceManager.GetString("CMDERR_ADD_BEHIND_ENDPOINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element &quot;{0}&quot; is alreadyPresent..
        /// </summary>
        internal static string CMDERR_ADDING_PRESENT {
            get {
                return ResourceManager.GetString("CMDERR_ADDING_PRESENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad cardinality format: .
        /// </summary>
        internal static string CMDERR_CARDINALITY_FORMAT {
            get {
                return ResourceManager.GetString("CMDERR_CARDINALITY_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action must be selected..
        /// </summary>
        internal static string CMDERR_COMMAND_ACTION_MISSING {
            get {
                return ResourceManager.GetString("CMDERR_COMMAND_ACTION_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandNumber should be assigned only once..
        /// </summary>
        internal static string CMDERR_COMMAND_NUMBER_ALTERED {
            get {
                return ResourceManager.GetString("CMDERR_COMMAND_NUMBER_ALTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing annotated element for new comment..
        /// </summary>
        internal static string CMDERR_COMMENT_ANNOTATED_ELEMENT_MISSING {
            get {
                return ResourceManager.GetString("CMDERR_COMMENT_ANNOTATED_ELEMENT_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create generalization, it would create cyclic inheritance..
        /// </summary>
        internal static string CMDERR_CYCLIC_INHERITANCE {
            get {
                return ResourceManager.GetString("CMDERR_CYCLIC_INHERITANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete root package. .
        /// </summary>
        internal static string CMDERR_DELETE_MODEL {
            get {
                return ResourceManager.GetString("CMDERR_DELETE_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete element &quot;{0}&quot; because it is not present in the diagram..
        /// </summary>
        internal static string CMDERR_DELETE_NONEXISTING {
            get {
                return ResourceManager.GetString("CMDERR_DELETE_NONEXISTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete association &quot;{0}&quot;. It has some PSM dependencies: {1}.
        /// </summary>
        internal static string CMDERR_DELETE_PSM_DEPENDENT_ASSOCIATION {
            get {
                return ResourceManager.GetString("CMDERR_DELETE_PSM_DEPENDENT_ASSOCIATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete PIM attribute &quot;{0}&quot;. It has some PSM dependencies..
        /// </summary>
        internal static string CMDERR_DELETE_PSM_DEPENDENT_ATTRIBUTE {
            get {
                return ResourceManager.GetString("CMDERR_DELETE_PSM_DEPENDENT_ATTRIBUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete PIM class &quot;{0}&quot;. It has some PSM dependencies: {1}.
        /// </summary>
        internal static string CMDERR_DELETE_PSM_DEPENDENT_CLASS {
            get {
                return ResourceManager.GetString("CMDERR_DELETE_PSM_DEPENDENT_CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram &apos;{0}&apos; cannot be deleted, it is not part of the project. .
        /// </summary>
        internal static string CMDERR_DIAGRAM_NOT_IN_PROJECT {
            get {
                return ResourceManager.GetString("CMDERR_DIAGRAM_NOT_IN_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If command should copy on stack (CopyOnStack returns true), command must implement ICopiedCommand interface..
        /// </summary>
        internal static string CMDERR_DOES_NOT_IMPLEMENT_ICOPIEDCOMMAND {
            get {
                return ResourceManager.GetString("CMDERR_DOES_NOT_IMPLEMENT_ICOPIEDCOMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found more of attribute &quot;{1}&quot; usages in class &quot;{0}&quot;..
        /// </summary>
        internal static string CMDERR_DUPLICATE_ATTRIBUTE {
            get {
                return ResourceManager.GetString("CMDERR_DUPLICATE_ATTRIBUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded attributes come from a different class..
        /// </summary>
        internal static string CMDERR_EXCLUDED_ATTRIBUTES_INCONSISTENCE {
            get {
                return ResourceManager.GetString("CMDERR_EXCLUDED_ATTRIBUTES_INCONSISTENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected path to {0} is already a part of another grouping..
        /// </summary>
        internal static string CMDERR_GROUP_BY_ALREADYGROUPED {
            get {
                return ResourceManager.GetString("CMDERR_GROUP_BY_ALREADYGROUPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected class cannot be grouped since it is not a root of the PSM tree!.
        /// </summary>
        internal static string CMDERR_GROUP_BY_NOTROOT {
            get {
                return ResourceManager.GetString("CMDERR_GROUP_BY_NOTROOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouped class or grouping classes are not set!.
        /// </summary>
        internal static string CMDERR_GROUP_BY_NOTSET {
            get {
                return ResourceManager.GetString("CMDERR_GROUP_BY_NOTSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot include element &quot;{0}&quot; in the collection because it is already a  member of another collection.
        /// </summary>
        internal static string CMDERR_INCLUDE_ELEMENT {
            get {
                return ResourceManager.GetString("CMDERR_INCLUDE_ELEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included attributes come from a different class..
        /// </summary>
        internal static string CMDERR_INCLUDED_ATTRIBUTES_INCONSISTENCE {
            get {
                return ResourceManager.GetString("CMDERR_INCLUDED_ATTRIBUTES_INCONSISTENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index is out of range..
        /// </summary>
        internal static string CMDERR_INDEX_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("CMDERR_INDEX_OUT_OF_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index of a moved item and new index for the moved item must be specified..
        /// </summary>
        internal static string CMDERR_INDICES_NOT_SPECIFIED {
            get {
                return ResourceManager.GetString("CMDERR_INDICES_NOT_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &quot;{0}&quot; was not correctly initialized, field &quot;{1}&quot; must be defined before execution..
        /// </summary>
        internal static string CMDERR_MANDATORY_ARGUMENT_NOT_INITIALIZED_2 {
            get {
                return ResourceManager.GetString("CMDERR_MANDATORY_ARGUMENT_NOT_INITIALIZED_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &quot;{0}&quot; must declare an empty constructor (the constructor may be private, internal,  protected, protected internal, or public)..
        /// </summary>
        internal static string CMDERR_MISSIING_NONPARAMETRIC_CONSTRUCTOR {
            get {
                return ResourceManager.GetString("CMDERR_MISSIING_NONPARAMETRIC_CONSTRUCTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must set associatiated classes..
        /// </summary>
        internal static string CMDERR_MISSING_ASSOCIATED_CLASSES {
            get {
                return ResourceManager.GetString("CMDERR_MISSING_ASSOCIATED_CLASSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must use PointMoveDataCollection when Action is EJunctionPointAction.MovePoints.
        /// </summary>
        internal static string CMDERR_MISSING_POINTMOVEDATACOLLECTION {
            get {
                return ResourceManager.GetString("CMDERR_MISSING_POINTMOVEDATACOLLECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModelElementAttribute can be used only once. Found more usages in class {0}.
        /// </summary>
        internal static string CMDERR_MODELELEMENT_DUPLICITY {
            get {
                return ResourceManager.GetString("CMDERR_MODELELEMENT_DUPLICITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModelElement attribute can used only on types supporting INotifyPropertyChanged interface..
        /// </summary>
        internal static string CMDERR_MODELELEMENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("CMDERR_MODELELEMENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower bound cannot be greater than upper bound..
        /// </summary>
        internal static string CMDERR_MULTIPLICITY_BAD_BOUNDS {
            get {
                return ResourceManager.GetString("CMDERR_MULTIPLICITY_BAD_BOUNDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name &quot;{0}&quot; cannot be used because it is already used in the collection. .
        /// </summary>
        internal static string CMDERR_NAME_NOT_UNIQUE {
            get {
                return ResourceManager.GetString("CMDERR_NAME_NOT_UNIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element &quot;{0}&quot; not found..
        /// </summary>
        internal static string CMDERR_NOT_FOUND {
            get {
                return ResourceManager.GetString("CMDERR_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UndoOperation&apos;s element is null..
        /// </summary>
        internal static string CMDERR_NULL_ON_UNDO {
            get {
                return ResourceManager.GetString("CMDERR_NULL_ON_UNDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parameters must be of type IList..
        /// </summary>
        internal static string CMDERR_PARAMETER_NOT_ILIST {
            get {
                return ResourceManager.GetString("CMDERR_PARAMETER_NOT_ILIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIM-less attribute must have a name specified..
        /// </summary>
        internal static string CMDERR_PIMLESS_NAME {
            get {
                return ResourceManager.GetString("CMDERR_PIMLESS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewHelperPointCollection must be set for action &quot;{0}&quot;..
        /// </summary>
        internal static string CMDERR_POINT_COLLECTION_MISSING {
            get {
                return ResourceManager.GetString("CMDERR_POINT_COLLECTION_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First and last point cannot be removed from a junction, only inner points can be removed..
        /// </summary>
        internal static string CMDERR_REMOVE_ENDPOINT {
            get {
                return ResourceManager.GetString("CMDERR_REMOVE_ENDPOINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete from model, element is being used. .
        /// </summary>
        internal static string CMDERR_REMOVED_ELEMENT_BEING_USED {
            get {
                return ResourceManager.GetString("CMDERR_REMOVED_ELEMENT_BEING_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove attribute which is not included in any element&apos;s attrributes. .
        /// </summary>
        internal static string CMDERR_REMOVING_DETACHED_ATTRIBUTE {
            get {
                return ResourceManager.GetString("CMDERR_REMOVING_DETACHED_ATTRIBUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove operation which is not included in any element&apos;s operation..
        /// </summary>
        internal static string CMDERR_REMOVING_DETACHED_OPERATION {
            get {
                return ResourceManager.GetString("CMDERR_REMOVING_DETACHED_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute representing PIM attribute can not change its datatype and name. .
        /// </summary>
        internal static string CMDERR_REPRESENTING_ATTRIBUTES_CAN_NOT_BE_UPDATED {
            get {
                return ResourceManager.GetString("CMDERR_REPRESENTING_ATTRIBUTES_CAN_NOT_BE_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result attribute &quot;{0}&quot; was not set during execution of the command {1}..
        /// </summary>
        internal static string CMDERR_RESULT_ARGUMENT_NULL {
            get {
                return ResourceManager.GetString("CMDERR_RESULT_ARGUMENT_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root class belongs to another diagram..
        /// </summary>
        internal static string CMDERR_ROOT_CLASS_WRONG_DIAGRAM {
            get {
                return ResourceManager.GetString("CMDERR_ROOT_CLASS_WRONG_DIAGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in command stack consistency..
        /// </summary>
        internal static string CMDERR_STACK_INCONSISTENT {
            get {
                return ResourceManager.GetString("CMDERR_STACK_INCONSISTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown action &quot;{0}&quot;..
        /// </summary>
        internal static string CMDERR_UNKNOWN_ACTION {
            get {
                return ResourceManager.GetString("CMDERR_UNKNOWN_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associations that have more then 2 ends must use association diamond. .
        /// </summary>
        internal static string DIAMOND_REQUIRED {
            get {
                return ResourceManager.GetString("DIAMOND_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only for PSM diagrams..
        /// </summary>
        internal static string NOT_PSM_DIAGRAM {
            get {
                return ResourceManager.GetString("NOT_PSM_DIAGRAM", resourceCulture);
            }
        }
    }
}
