//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCase.Model.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XCase.Model.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!-- project containing one empty PIM diagram, this template is used when new project is created in XCase --&gt;
        ///&lt;xc:project xmlns:xc=&quot;http://kocour.ms.mff.cuni.cz/~necasky/xcase&quot; version=&quot;2.0&quot;&gt;
        ///	&lt;xc:uml&gt;
        ///		&lt;xc:primitive_types /&gt;
        ///		&lt;xc:profiles /&gt;
        ///		&lt;xc:model id=&quot;26&quot; name=&quot;User model&quot; viewpoint=&quot;&quot; namespace=&quot;&quot;&gt;
        ///			&lt;xc:comments /&gt;
        ///			&lt;xc:datatypes /&gt;
        ///			&lt;xc:packages /&gt;
        ///			&lt;xc:pim_classes /&gt;
        ///			&lt;xc:associations /&gt;
        ///			&lt;xc:generalizations /&gt;
        ///		&lt;/xc:model&gt;
        ///	&lt;/xc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmptyProject {
            get {
                return ResourceManager.GetString("EmptyProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- 
        ///This template containse basic primitive types and neccessary PSM stereotypes. It is 
        ///a core of every XCase model and should not be altered by users. 
        ///--&gt;
        ///&lt;xc:project xmlns:xc=&quot;http://kocour.ms.mff.cuni.cz/~necasky/xcase&quot; version=&quot;2.0&quot;&gt;
        ///  &lt;xc:uml&gt;
        ///    &lt;xc:primitive_types&gt;
        ///      &lt;xc:datatype id=&quot;27&quot; description=&quot;int&quot;       name=&quot;integer&quot;  simple=&quot;True&quot; /&gt;
        ///      &lt;xc:datatype id=&quot;28&quot; description=&quot;string&quot;    name=&quot;string&quot;   simple=&quot;True&quot; /&gt;
        ///      &lt;xc:datatyp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProjectStub {
            get {
                return ResourceManager.GetString("ProjectStub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;windows-1250&quot;?&gt;
        ///&lt;!-- ..................................................................--&gt;
        ///&lt;!--                                                                   --&gt;
        ///&lt;!--                   XCase Project XML Schema                        --&gt;
        ///&lt;!--                                                                   --&gt;
        ///&lt;!--     This XML schema describes the structure and datatypes         --&gt;
        ///&lt;!--     of a XML file with one serialized XCase project.              --&gt;
        ///&lt;!--      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XCaseSchema {
            get {
                return ResourceManager.GetString("XCaseSchema", resourceCulture);
            }
        }
    }
}
